import 'package:dio/dio.dart';
import 'package:retrofit/error_logger.dart';
import 'package:retrofit/http.dart';
import '../models/country_model.dart';

part 'api_client.g.dart'; // Part directive to include the generated Retrofit code

// Retrofit API client for accessing the REST Countries API
@RestApi(baseUrl: "https://restcountries.com/v3.1/") // Base URL for the API
abstract class ApiClient {
  // Factory constructor for creating an instance of ApiClient
  // The implementation is generated by Retrofit and stored in 'api_client.g.dart'
  factory ApiClient(Dio dio, {String baseUrl}) = _ApiClient;

  // GET request to fetch European countries with specific fields
  @GET("region/europe?fields=name,capital,flags,region,languages,population")
  Future<List<CountryModel>> getEuropeanCountries();
}
